### PR TITLE
@rbrundritt Optimize polygon encoding

### PR DESCRIPTION
**Pull request by rbrundritt**
Improved the polygon encoding code. Originally it was skipping any polygons with an area of 0. This pull requests now skips any polygons that will cover an area of less than 1 pixel within a tile.

### CODE REVIEW

**Comment by FObermaier** [comment]
Thanks for the suggestion to optimize, I'm wondering if it would be even better to check if `Geometry.EnvelopeInternal.MaxExtent` is larger than the width or height of tile pixel?

**Comment by xivk** [comment]
+1 on @FObermaier 's suggestion, I was meaning to do this myself when I had the time... 👍👍

**Comment by rbrundritt** [comment]
Before I make this change, want to run the logic by you guys to make sure I understand correctly. 

Option 1: This option would require minimal calculations. 

1. Calculate the minimum degrees per pixels in the latitude (at 85.5 degrees) and longitude (at 0 degrees) directions (these will likely differ).
2. Loop through all features, for polygons encoding, pass in these min values. Grab the Geometry.EnvelopeInternal.MaxExtent value, compare width to min longitude degrees per pixel, and max latitude degrees per pixel. 

Option 2: This would require more calculations, but would be more accurate and may filter out more polygons.

When encoding each polygon, get the Geometry.EnvelopeInternal.MaxExtent, then take two opposite corners and convert lat/lon to meters, then meters to pixels, and ensure that width/height is at least 1 pixel.

**Comment by xivk** [comment]
For me option 1 is good already because it's simple and already an improvement over what we have now.

Perhaps at a later time it can be a good idea to calculate the min degrees per pixel relative to the tile position. We could also when we encode the tiles into mvt format leave out the polygons that are too small, one pixel or less for example.

**Comment by rbrundritt** [comment]
Thinking about this more, I think option 2 is the way to go. Using option 1, the degrees per pixel difference at the equator compared to 85.5 degrees latitude is 10x. This means that the closer your data is to the equator, the more sub-pixel sized polygons that will get through. Option 2 is a bit more calculations, but much more accurate and efficient. This will ensure smaller tile sizes that will benefit both pre-generated and on demand generate tile scenarios (saved latency time likely much greater than extra processing time).

**Comment by rbrundritt** [comment]
Modified the logic to use the envelope corners to calculate pixel width/height. Works faster than before for me as its more aggressive in weeding out polygons and thus saving calculations later.

**Comment by rbrundritt** [comment]
I'll change the name. 

For && vs ||. With || a polygon could have a width of 1 and a larger height would end up being rendered as a line. With && a polygon has to have a more meaningful area. If I move to || I'll have to add extra logic to handle 0 width/heights.

**Review by FObermaier — APPROVED** [review]
Thanks a lot.

**Comment by xivk** [comment]
Yes! Thanks @rbrundritt 🥇 and @FObermaier for reviewing!

**Pull request merged**
