### PR TITLE
Fix misplacement of geometry parts

### LINKED ISSUE #29: MVT Writer Geometry shift
Encountered an issue when writing an mvt where some of the geometries are shifted to a wrong location.
for the same geometry, higher and lower zoom display different behaviours.
In low zoom (4) the some of the polygons are not where they should be.
in high zoom (6) the issue is not reproduced.

Geometry used in test:
[Italy.txt](https://github.com/NetTopologySuite/NetTopologySuite.IO.VectorTiles/files/14634179/Italy.txt)

`        

        
        [Test]
        public void MvtWriterGeometryIssue()
        {
            writeTile(8, 6, 4);
            writeTile(34,24,6);
        }

        private static void writeTile(int x, int y, int z)
        {
            string italyTxt = getItalyText();
            Geometry geometry = new WKTReader().Read(italyTxt);
            Feature feature = new Feature(geometry, new AttributesTable(new Dictionary<string, object>()
            {
                { "id", 1 }
            }));
            Tile tileDefinition = new Tile(x, y, z);
            VectorTile vectorTile = new VectorTile { TileId = tileDefinition.Id };
            Layer layer = new Layer { Name = "layer1" };
            vectorTile.Layers.Add(layer);
            layer.Features.Add(feature);

            byte[] result;
            MemoryStream? ms;
            using (ms = new MemoryStream(1024 * 32))
            {
                vectorTile.Write(ms);
                result = ms.ToArray();
            }

            File.WriteAllBytes($"{x}_{y}_{z}.mvt", result);
        }

        private static string getItalyText() => File.ReadAllText("Italy.wkt");

Opend the tiles in QGIS, with an OSM layer in background to see the shift.

Original geometry:
2024-03-18_11h00_48

Tile x=8,y=6,z=4

2024-03-18_11h24_14

Tile x=34,y=24,z=6

2024-03-18_11h29_28

### PR DESCRIPTION
**Pull request by FObermaier**
If components of geometries are too small to be encoded at the provided zoom level the encoded data is deleted in `Encode(CoordinateSequence seq, ..., ref int currentX, ref int currentY, ...)` but the values of `currentX` and `currentY`  are not reset to their initial values. This causes all subsequent geometry items to have a wrong offset.

This PR fixes this by
* storing initial currentX and currentY values, and reseting their values when encoded data is deleted.
* checking for all geometry components individually if their extent exceeds 1 pixel in the tile at the given zoom level.

closes #29

### CODE REVIEW

**Comment by FObermaier** [comment]
@rbrundritt, @xivk, @kolyanch
I'd like your opinion on whether or not we should check if the extent of an encoded `LineString` exceeds 1 pixel and only write it to the tile if it does:

https://github.com/NetTopologySuite/NetTopologySuite.IO.VectorTiles/blob/556e70c79d67de34e788d0cc3f4c6c66cbbfad2e/src/NetTopologySuite.IO.VectorTiles.Mapbox/MapboxTileWriter.cs#L236-L249

**Comment by kolyanch** [comment]
I believe that the processing of small objects should be the same for polygonal and linear objects. I opened the MVT specification, there is nothing about linear objects. But there is a strict rule for polygonal ones:
> A linear ring SHOULD NOT have an area calculated by the surveyor's formula equal to zero, as this would signify a ring with anomalous geometric points

In short I vote for checks for linear objects)

**Comment by rbrundritt** [comment]
I did think about this, as well as the 1-pixel area polygon scenario (or user defined minimums). The main issue I've ran into in the past with this is you end up in scenarios where the end user is zoomed out and you have an empty map and can't see where the data is. I've found that it is often better to show 1-pixel for lines/polygons in this scenario, at least from a real-world user experience perspective. That said, it would depend on your data set. If you are showing a single data set, it's nice to have these show, but if you have multiple datasets where shapes are different sizes, then it may be desirable to not have the smaller shapes appear. 

With all this in mind, having a configuration setting on a per layer level, where the minimum area/length of a polygon/line could be set, would be a "nice to have" feature. But this definitely shouldn't be forced.

**Comment by xivk** [comment]
I also believe by default we should drop anything that is too small. I even thought this was the default behavior, I have some checking to do on some of our services now...

**Review by rbrundritt — APPROVED** [review]

**Review by kolyanch — APPROVED** [review]

**Pull request merged**
